accounting/urls.py
from django.urls import path
from . import views

app_name = 'accounting'

urlpatterns = [
    path('add', views.add_invoice, name='add_invoice'),
    path('invoices', views.invoices, name='invoices'),
    path('payment/<int:invoice_id>/', views.rec_payment, name='rec_payment')
]

contacts/urls.py
from django.urls import path
from . import views


app_name = 'contacts'

urlpatterns = [
    path('all/', views.all, name='all'),
    path('add/', views.add, name='add'),
    path('contact/<int:contact_id>/', views.contact, name='contact'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index')
]

leases/urls.py
from django.urls import path
from . import views

app_name = 'leases'

urlpatterns = [
    path('all/', views.all, name='all'),
    path('active/', views.active, name='active'),
    path('add/', views.add, name='add'),
    path('add/<int:unit_id>/', views.add, name='add')
]

properly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('properties/', include('properties.urls')),
    path('contacts/', include('contacts.urls')),
    path('leases/', include('leases.urls')),
    path('accounting/', include('accounting.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.logout_view, name='logout'),
    path('logout/', views.register, name='register'),
    
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect, reverse

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        return redirect(reverse('properties:all'))
    else:
        return render(request, 'home/index.html')

home/templates/home/base.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet"  href="{% static 'home/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
    <title>

        {% block title %}
        
        {% if title %}
            Properly | {{title}}
        {% else %}
            Properly
        {% endif %}
            
        {% endblock title %}

    </title>
</head>

<body class="bg-1">
    {% include 'home/nav.html' %}

    <div class="container px-4 d-flex justify-content-between flex-wrap">

        <h3>{{title}}</h3>
        {% block header %}
        
        {% endblock header %}
        
    </div>
    
    <div class="container mb-3 p-4 ">
    
            {% block body %}
            
            {% endblock body %}

    </div>
    
</body>

</html>

home/templates/home/index.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

    <title>

        {% block title %}

        {% if title %}
        Properly | {{title}}
        {% else %}
        Properly
        {% endif %}

        {% endblock title %}

    </title>
</head>

<body id="home">
    {% include 'home/nav.html' %}

    <div class="container px-4 d-flex justify-content-between flex-wrap">

        <h3>{{title}}</h3>
        {% block header %}

        {% endblock header %}

    </div>

    <div class="container mb-3 p-4 ">

        {% block body %}



        <div class="text-center col-12 col-lg-6 mx-auto p-4 text-white rounded" style="background-color: rgba(0, 0, 0, 0.6);">
            
            <h2 class="display-3">Properly</h2>
            <br>
            <h2 class="font-weight-light">Manage Properties Easily!</h2>
            <br>
            <hr>
            <br>

            <div class="d-flex justify-content-around flex-wrap">

                <div class="col-lg-7 col-md-12">
                    <h2 class="text-center">Have an account?</h2>
                    <a class="btn btn-primary col-12" href="{% url 'users:login' %}" type="button">Login</a>
                </div>
                
                <div class="col-lg-7 col-md-12">
                    <h2 class="text-center">New to Properly?</h2>
                    <a class="btn btn-primary col-12" href="{% url 'users:register' %}" type="button">Register now!</a>
                </div>

            </div>

            <br>
            
        </div>



        {% endblock body %}

    </div>

</body>

</html>

home/templates/home/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-d sticky-top shadow-sm">

    <a class="navbar-brand" href="{% url 'home:index' %}">
        <strong style="font-style: ;">
            <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-house-fill" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M8 3.293l6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z" />
                <path fill-rule="evenodd"
                    d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z" />
            </svg>
            Properly
        </strong>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <!---------------------------------------------------------------- Navbar middle ------------------------------------------------------->
        
        
        <ul class="navbar-nav mr-auto mx-auto">
            {% if request.user.is_authenticated %}

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:index' %}">Home<span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Properties
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'properties:all' %}">Properties</a>
                    <a class="dropdown-item" href="{% url 'properties:units' %}">Units</a>

                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" href="{% url 'properties:add' %}">Add Property</a>
                </div>

            </li>

            <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Contacts
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'contacts:all' %}">All Contacts</a>

                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" href="{% url 'contacts:add' %}">Add Contact</a>
                </div>

            </li>

            <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Leases
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'leases:all' %}">All Leases</a>
                    <a class="dropdown-item" href="{% url 'leases:active' %}">Active Leases</a>

                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" href="{% url 'leases:add' %}">Add Lease</a>
                </div>

            </li>

            <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Accounting
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href=" {% url 'accounting:invoices' %} ">Invoices</a>

                    <!-- <div class="dropdown-divider"></div> -->

                    <!-- <a class="dropdown-item" href=" {% url 'accounting:add_invoice' %} ">Add Invoice</a>
                    <a class="dropdown-item" href="#">Something else here</a> -->
                </div>

            </li>

            <!-- <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Manage
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Manage Properties</a>

                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>

                </div>

            </li> -->


            <!-- <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li> -->

            {% endif %}
        </ul>

        <!---------------------------------------------------------------- Navbar middle ------------------------------------------------------->

        <!--------------------------------------------------------------- Navbar right side ---------------------------------------------------->
        <ul class="navbar-nav float-lg-right">

            {% if user.is_authenticated %}

            <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Welcome {{user.username|title}}!
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'home:index' %}">{{user.username|title}}</a>

                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                </div>

            </li>
            <!-- 
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'home:index' %}">Welcome {{user.username|title}}!</a>
            </li> -->

            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>

            {% endif %}

        </ul>
        <!--------------------------------------------------------------- Navbar right side ---------------------------------------------------->

    </div>

</nav>
<br>