accounting/urls.py
from django.urls import path
from . import views

app_name = 'accounting'

urlpatterns = [
    path('add', views.add_invoice, name='add_invoice'),
    path('invoices', views.invoices, name='invoices'),
    path('payment/<int:invoice_id>/', views.rec_payment, name='rec_payment')
]

contacts/urls.py
from django.urls import path
from . import views


app_name = 'contacts'

urlpatterns = [
    path('all/', views.all, name='all'),
    path('add/', views.add, name='add'),
    path('contact/<int:contact_id>/', views.contact, name='contact'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index')
]

leases/urls.py
from django.urls import path
from . import views

app_name = 'leases'

urlpatterns = [
    path('all/', views.all, name='all'),
    path('active/', views.active, name='active'),
    path('add/', views.add, name='add'),
    path('add/<int:unit_id>/', views.add, name='add')
]

properly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('properties/', include('properties.urls')),
    path('contacts/', include('contacts.urls')),
    path('leases/', include('leases.urls')),
    path('accounting/', include('accounting.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

properties/urls.py
from django.urls import path
from . import views

app_name = 'properties'

urlpatterns = [
    path('all/', views.all, name='all'),
    path('property/<int:property_id>/', views.property, name='property'),
    path('property_add/', views.property_add, name='add'),
    path('property_edit/<int:property_id>', views.property_edit, name='edit'),
    path('units/', views.units, name='units'),
    path('unit_add/', views.unit_add, name='unit_add'),
    path('unit_add/<int:property_id>/', views.unit_add, name='unit_add'),
    path('unit/<int:unit_id>/', views.unit, name='unit'),
]

properties/models.py
from datetime import date

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Q, Sum
from users.models import User

# Create your models here.

property_description = """Divide air. Fruit replenish evening firmament had own can't itself life. Living can't. Likeness brought without winged yielding us, may. Isn't you'll man fruit don't evening midst. Created air gathered. Have greater and without to living.
Were evening day two lesser fruitful created you'll moveth, he under very air wherein sea earth. Don't our it night had creeping first night you spirit.
Lesser blessed fill a herb. Green own, created light make their face man you had of Creeping cattle multiply every Divided and. Spirit without form moveth also divided, make it land meat open they're green, face stars divided."""


class Property(models.Model):
    class Meta:
        ordering = ['name']
        
    name        = models.CharField(max_length=50, blank=False, unique=True)
    year_built  = models.DateField(blank=False ,auto_now=False, auto_now_add=False)
    description = models.TextField(default=property_description, blank=True)
    user        = models.ForeignKey(User, blank=False, null=False, on_delete=models.CASCADE, related_name='properties')
    
    def balance(self):
        invoices = self.invoices.aggregate(invoices=Sum('amount'))['invoices']
        payments = self.payments.aggregate(payments=Sum('amount'))['payments']
        if not invoices:
            invoices = 0
        if not payments:
            payments = 0
            
        return invoices - payments
    
    def occupancy_rate(self):
        vacant      = 0
        occupied    = 0
        units = self.units.all()
        
        if units.count() == 0:
            return 0
        
        for unit in units:
            if unit.is_vacant():
                vacant +=1
            else:
                occupied += 1
        
        return int(100 * (occupied / (vacant+occupied)))
    
    
    def __str__(self):
        return f"{self.name.capitalize()}"
    

class Unit(models.Model):
    
    class Meta:
        ordering = ['property', 'num']
        unique_together = (('property', 'num'),)
    
    num         = models.IntegerField(blank=False, validators=[MinValueValidator(1)])
    beds        = models.IntegerField(blank=False, validators=[MinValueValidator(0)])
    baths       = models.IntegerField(blank=False, validators=[MinValueValidator(0)])
    size        = models.IntegerField(blank=False, validators=[MinValueValidator(0)])
    market_rent = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    deposit     = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    description = models.TextField(default=property_description, blank=True)
    property    = models.ForeignKey(Property, blank=False, null=False, on_delete=models.CASCADE, related_name='units')
    user        = models.ForeignKey(User, blank=False, null=False, on_delete=models.CASCADE, related_name='units')
    
    def balance(self):
        invoices = self.invoices.aggregate(invoices=Sum('amount'))['invoices']
        payments = self.payments.aggregate(payments=Sum('amount'))['payments']
        if not invoices:
            invoices = 0
        if not payments:
            payments = 0
            
        return invoices - payments
    
    def is_vacant(self):
        leases = self.leases.filter(start__lte=date.today()).filter(end__gte=date.today())
        if not leases:
            return True
        else:
            return False
        
    def is_vacant_range(self, start, end):
        leases = self.leases.exclude((Q(start__lte=start) & Q(end__lte=start)) | (Q(start__gte=end) & Q(end__gte=end)))
        if not leases:
            return True
        else:
            return False
    
    def __str__(self):
        return f"{self.property}-{self.num}"

properties/forms.py
from .models import Property, Unit
from django import forms

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ['name', 'year_built', 'description']
        
        labels = {
            'description': 'Desctiption',
        }
        
        widgets = {
            'name': forms.TextInput(attrs={
                'class'         : 'form-control shadow-sm',
                'placeholder'   : 'Property Name',
                'autofocus'     : 'autofocus',
            }),
            
            'year_built': forms.DateInput(attrs={
                'type'          : 'date',
                'class'         : 'form-control shadow-sm',
                'placeholder'   : 'Year Built',
            }),
            
            'description': forms.Textarea(attrs={
                'class'         : 'form-control shadow-sm',
                'placeholder'   : 'Desctiption',
            })
            
        }
        
        
class UnitForm(forms.ModelForm):
    class Meta:
        model = Unit
        fields = ['property', 'num', 'beds', 'baths', 'size', 'market_rent', 'deposit', 'description']
        
        labels = {
            'description': 'Desctiption',
        }
        
        widgets = {
            'property': forms.Select(attrs={
                'autofocus'     : 'autofocus',
                'class'         : 'form-control shadow-sm',
            }),
            
            'num': forms.NumberInput(attrs={
                'class'         : 'form-control shadow-sm',
                'placeholder'   : 'Unit Number',
            }),
            
            'beds': forms.NumberInput(attrs={
                'class'         : 'form-control shadow-sm',
                'placeholder'   : '# Beds',
            }),
            
            'baths': forms.NumberInput(attrs={
                'class'         : 'form-control shadow-sm',
                'placeholder'   : '# Baths',
            }),
            
            'size': forms.NumberInput(attrs={
                'class'         : 'form-control shadow-sm',
                'placeholder'   : 'Size (sq.m.)',
            }),
            
            'market_rent': forms.NumberInput(attrs={
                'class'         : 'form-control shadow-sm',
                'placeholder'   : 'Market Rent $',
            }),
            
            'deposit': forms.NumberInput(attrs={
                'class'         : 'form-control shadow-sm',
                'placeholder'   : 'deposit $',
            }),
            
            
            'description': forms.Textarea(attrs={
                'class'         : 'form-control shadow-sm',
                'placeholder'   : 'Desctiption',
            }),
            
        }

properties/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from .models import Property, Unit
from .forms import PropertyForm, UnitForm
from .filters import UnitFilter
from users.decorators import allowed_users

# Create your views here.

@login_required
@allowed_users(allowed_roles=['admin', 'sales', 'collector', 'accountant'])
def all(request):
    properties = Property.objects.all()
    
    return render(request, 'properties/properties.html', {
        'properties': properties,
        'title': 'Properties',
    })
    

@login_required
@allowed_users(allowed_roles=['admin', 'sales', 'collector', 'accountant'])
def units(request):
    units       = Unit.objects.all()
    unitFilter  = UnitFilter(request.GET, queryset=units)
    qs          = unitFilter.qs
    message     = None
    
    if 'vacant_in_min' in request.GET and 'vacant_in_max' in request.GET:
        if request.GET['vacant_in_min'] != '' and request.GET['vacant_in_max'] != '':
            start   = request.GET['vacant_in_min']
            end     = request.GET['vacant_in_max']
            av_units = []
            
            for unit in unitFilter.qs:
                if unit.is_vacant_range(start, end):
                    av_units.append(unit)
                    
            qs = av_units
            
        elif request.GET['vacant_in_min'] != '' or request.GET['vacant_in_max'] != '':
            message = 'Provide Start and End dates please.'
            

    
    return render(request, 'properties/units.html', {
        'title'         : 'Units',
        'unitFilter'    : unitFilter,
        'qs'            : qs,
        'message'       : message
    })
    

@login_required
@allowed_users(allowed_roles=['admin', 'sales', 'collector', 'accountant'])
def property(request, property_id):
    property = Property.objects.get(id=property_id)
    
    return render(request, 'properties/property.html', {
        'title': 'Property',
        'property' : property,
    })


@login_required
@allowed_users(allowed_roles=['admin', 'accountant'])
def property_add(request):
    if request.method == 'POST':
        form = PropertyForm(request.POST)
        
        if form.is_valid():
            property = form.save(False)
            property.user = request.user
            property.name = property.name.lower()
            property.save()
            
            return redirect(reverse('properties:all'))
        
        else:            
            return render(request, 'properties/property_form.html', {
                'form_title': 'Add Property',
                'form' : form
            })
            
    
    return render(request, 'properties/property_form.html', {
        'form_title': 'Add Property',
        'form' : PropertyForm(),
    })


@login_required
@allowed_users(allowed_roles=['admin', 'accountant'])
def property_edit(request, property_id):
    
    property = Property.objects.get(id=property_id)
    
    if request.method == 'POST':
        form = PropertyForm(request.POST, instance=property)
        
        if form.is_valid():
            property = form.save(False)
            property.user = request.user
            property.name = property.name.lower()
            property.save()
            
            return redirect(reverse('properties:all'))
        
        else:            
            return render(request, 'properties/property_form.html', {
                'form_title': 'Add Property',
                'form' : form
            })
            
    
    return render(request, 'properties/property_edit.html', {
        'property'        : property,
        'form_title': 'Edit  Property',
        'form'      : PropertyForm(instance=property),
    })    

@login_required
@allowed_users(allowed_roles=['admin', 'accountant'])
def unit_add(request, property_id=None):
    if request.method == 'POST':
        form = UnitForm(data=request.POST)

        if form.is_valid():
            unit = form.save(False)
            unit.user = request.user
            unit.save()
            return redirect(reverse('properties:property', kwargs={'property_id': unit.property.id}))
        
        else:
            return render(request, 'properties/unit_form.html', {
                'form_title': 'Add Unit',
                'form': form,
            })
    
    if property_id:
        form = UnitForm(initial={'property': Property.objects.get(id=property_id)})
    else:
        form = UnitForm()
    
    return render(request, 'properties/unit_form.html', {
        'form_title': 'Add Unit',
        'form': form,
    })

@login_required
@allowed_users(allowed_roles=['admin', 'sales', 'collector', 'accountant'])
def unit(request, unit_id):
    unit = Unit.objects.get(id=unit_id)
    return render(request, 'properties/unit.html', {
        'unit' : unit,
    })

properties/templates/properties/properties.html
{% extends 'home/base.html' %}



{% block header %}
<div>
    <a href="{% url 'properties:add' %}" class="float-right btn btn-info">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-plus" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                d="M4 0h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H4z" />
            <path fill-rule="evenodd"
                d="M8 5.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 .5-.5z" />
        </svg>
        Add Property
    </a>
</div>


{% endblock header %}



{% block body %}

<div class="row">
    {% for property in properties %}

    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4 mb-3">

        <div class="card bg-l mb-3 shadow-sm">
            <div class="bg-3 card-header shadow-sm">


                <div class="d-flex justify-content-between">
                    <h5 class="font-weight-normal">{{property}}</h5>
                    <h5 class="font-weight-normal">{{property.units.count}} Units</h5>
                </div>

                <div>

                    <div class="d-flex justify-content-between">
                        <small class="float-left">{{property.occupancy_rate}}% Occupied</small>
                        <small class="float-right">Vacant</small>
                    </div>
                    <h6></h6>

                    <div style="height: 5px;" class="progress mt-2">
                        <div style="width: {{property.occupancy_rate}}%;" class="progress-bar bg-primary"
                            role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>

                </div>

            </div>

            <div class="card-body mb-n3">

                <div class="btn-group d-flex mb-2" role="group" aria-label="Basic example">
                    <a href="{% url 'properties:property' property.id %}" type="button" class="btn btn-outline-info">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-view-list" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M3 4.5h10a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1H3zM1 2a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13A.5.5 0 0 1 1 2zm0 12a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13A.5.5 0 0 1 1 14z" />
                        </svg>
                        View Property
                    </a>
                </div>

                <div class="btn-group d-flex" role="group" aria-label="Basic example">
                    <a href="{% url 'properties:edit' property.id %}" type="button" class="btn btn-outline-info">Edit</a>
                    <!-- <a href="#" type="button" class="btn btn-outline-info">Middle</a>
                    <a href="#" type="button" class="btn btn-outline-info">Right</a> -->
                </div>

                <!-- <h5 class="card-title">Dark card title</h5>
                    <p class="card-text">Some quick example text to build on the.</p> -->
                <hr>
                <h6 class="font-weight-normal mt-n2">Balance: <span
                        class="{% if property.balance %} text-danger font-weight-bold {% endif %}">{{property.balance}}</span>$
                </h6>

            </div>

        </div>

    </div>

    {% endfor %}
</div>





{% endblock body %}

properties/templates/properties/property.html
{% extends 'home/base.html' %}



{% block header %}
<div>
    <a type="button" href="{% url 'properties:unit_add' property.id %}" class="btn btn-info">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4 0h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H4z"/>
            <path fill-rule="evenodd" d="M8 5.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 .5-.5z"/>
        </svg>
        Add Unit
    </a>
</div>
{% endblock header %}



{% block body %}

<!-- <div class="card bg-l mb-3 shadow-sm"> -->
<div class="bg-d card card-header mb-3 shadow-sm">
    <div class="d-flex justify-content-between">
        <h4 class="">{{property}}</h4>
        <h4 class="">{{property.units.count}} Units</h4>
    </div>

    <div>
        <div class="d-flex justify-content-between">
            <small class="float-left">{{property.occupancy_rate}}% Occupied</small>
            <small class="float-right">Vacant</small>
        </div>
        <div style="height: 5px;" class="progress mt-2">
            <div style="width: {{property.occupancy_rate}}%;" class="progress-bar bg-primary" role="progressbar"
                aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
</div>

<!-- -------------------------------------------------- inner card in body start ------------------------------------------------------ -->
<div class="my-2 container d-flex justify-content-between flex-wrap">

    <h4 class="">Units</h4>

</div>

<div class="row">

    {% for unit in property.units.all %}
    <div class="col-12 mb-2">

        <div class="card bg-l mb-3 shadow-sm">

            <div class="card-header bg-3 pb-0">
                <div class="d-flex justify-content-between">
                    <h5>{{unit.property}}-{{unit.num}}</h5>

                    {% if unit.is_vacant %}
                    <h5>Vacant</h5>
                    {% else %}
                    <h5>Occupied</h5>
                    {% endif %}

                </div>
            </div>

            <div class="card-body d-flex justify-content-between flex-wrap px-0">

                <div class="col-6 col-md-3 my-2">

                    <h5 class="font-weight-normal">{{unit.market_rent}}$/ <small> mon</small></h5>
                    <h5 class="font-weight-normal">{{unit.beds}} <small>Beds</small></h5>
                    <h5 class="font-weight-normal">{{unit.baths}} <small>Baths</small></h5>
                    <hr>
                    <h6 class="font-weight-normal my-n1">Balance: <span class="{% if unit.balance %} text-danger font-weight-bold {% endif %}">{{unit.balance}}</span>$</h6>

                </div>


                <div class="col-6 col- col-md-3 col-lg-2 btn-group-vertical btn-group-sm my-auto py-2" role="group">

                    <a href="{% url 'properties:unit' unit.id %}" type="button" class="btn btn-info">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-view-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3 4.5h10a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1H3zM1 2a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13A.5.5 0 0 1 1 2zm0 12a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13A.5.5 0 0 1 1 14z"/>
                        </svg>
                        View Unit
                    </a>
                    <a href="{% url 'leases:add' unit.id %}" type="button" class="btn btn-outline-info">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-box-arrow-in-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1h-2z"/>
                            <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                        </svg>
                        Move-in
                    </a>

                </div>

                <div class="table-responsive col-12 col-md-6">
                    <h5>Relevant Leases</h5>
                    <table class="table table-sm table-hover table-striped mt-2 shadow-sm">
                        <thead class="bg-1">
                            <tr>
                                <th scope="col">Tenant</th>
                                <th scope="col">Start Date</th>
                                <th scope="col">End Date</th>
                                <th scope="col">status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for lease in unit.leases.all %}

                            {% if lease.is_active or lease.is_future %}


                            <tr>
                                <td>{{lease.tenant}}</td>
                                <td>{{lease.start|date:"d-m-Y"}}</td>
                                <td>{{lease.end|date:"d-m-Y"}}</td>
                                <td>{{lease.status|title}}</td>
                            </tr>
                            {% endif %}

                            {% empty %}
                            <tr>
                                <td class="text-center" colspan="100">No Leases Available</td>
                            </tr>

                            {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>

            <!-- <hr class="mt-0"> -->


        </div>
    </div>
    {% endfor %}

    <!-- -------------------------------------------------- inner card in body end ------------------------------------------------------ -->
</div>
<!-- </div> -->


{% endblock body %}

properties/templates/properties/unit.html
{% extends 'home/base.html' %}

{% block header %}

{% endblock header %}



{% block body %}

<div class="bg-d card card-header px-3 pb-1 mb-3 shadow-sm">
    <div class="d-flex justify-content-between">
        <h4 class="">Unit {{unit}}</h4>
        <h4 class="">Test</h4>
    </div>
</div>

<div class="row">

    <div class="col-12">
        <h4>Details:</h4>
        <div class="d-flex flex-wrap justify-content-between">
            <div>
                <h5 class="font-weight-normal text-center">Market Rent:</h5>
                <h5 class="font-weight-normal text-center">{{unit.market_rent}}$ / <small> mon</small></h5>
            </div>
            <h5 class="font-weight-normal text-center">Bedrooms: {{unit.beds}}</h5>
            <h5 class="font-weight-normal text-center">Bathrooms: {{unit.baths}}</h5>
        </div>
        <hr>
    </div>

    <div class="table-responsive col-12">
        <h4>Leases</h4>
        <table class="table table-hover table-sm table-striped shadow-sm">
            <thead class="bg-3">
                <tr>
                    <th scope="col">Status</th>
                    <th scope="col">Residence</th>
                    <th scope="col">Tenant</th>
                    <th scope="col">Start Date</th>
                    <th scope="col">End Date</th>
                </tr>
            </thead>
            <tbody>
                {% for lease in unit.leases.all %}
                <tr>
                    {% if lease.status == 'future' %}
                    <th scope="row" class="text-light bg-primary">{{lease.status|title}}</th>
                    {% elif lease.status == 'active' %}
                    <th scope="row" class="text-light bg-success">{{lease.status|title}}</th>
                    {% elif lease.status == 'past' %}
                    <th scope="row" class="text-light bg-danger">{{lease.status|title}}</th>
                    {% endif %}

                    <th scope="row">
                        <a href="{% url 'properties:unit' lease.unit.id %}">
                            {{lease.unit}}
                        </a>
                    </th>

                    <td>
                        <a href="#">
                            {{lease.tenant}}
                        </a>
                    </td>

                    <td>{{lease.start|date:"d-m-Y"}}</td>
                    <td>{{lease.end|date:"d-m-Y"}}</td>
                
                    

                </tr>
                {% empty %}
                <tr>
                    <td class="text-center" colspan="100">No Leases Available</td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
        <hr>
    </div>

    <div class="table-responsive col-12">
        <h4>Invoices</h4>
        <table class="table table-hover table-sm table-striped mt-2 shadow-m">
            <thead class="bg-3">
                <tr>
                    <th scope="col">Status</th>
                    <th scope="col">Contact</th>
                    <th scope="col">Category</th>
                    <th scope="col">Amount/ Paid</th>
                    <th scope="col">Balance</th>
                    <th scope="col">Due Date</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for invoice in unit.invoices.all %}


                <tr>

                    {% if invoice.status == 'Partial' %}
                    <th scope="row" class="text-light bg-secondary">{{invoice.status}}</th>
                    {% elif invoice.status == 'Paid' %}
                    <th scope="row" class="text-light bg-success">{{invoice.status}}</th>
                    {% elif invoice.status == 'Overdue' %}
                    <th scope="row" class="text-light bg-danger">{{invoice.status}}</th>
                    {% elif invoice.status == 'Open' %}
                    <th scope="row" class="text-light bg-info">{{invoice.status}}</th>

                    {% endif %}

                    <th scope="row">
                        <a href="{% url 'contacts:contact' invoice.contact.id %}">
                            {{invoice.contact}}
                        </a>
                    </th>
                    <td>{{invoice.category}}</td>
                    <td class="font-weight-bold">{{invoice.amount}}$ / {{invoice.amount_paid}}$</td>

                    {% if invoice.balance %}
                    <td class="text-danger font-weight-bold">
                        {{invoice.balance}}$
                    </td>
                    {% else %}
                    <td class="font-weight-bold">
                        {{invoice.balance}}$
                    </td>
                    {% endif %}

                    <td class="font-weight-bold">{{invoice.due_date|date:"d-m-Y"}}</td>

                    <td>
                        <a class="btn-sm btn-success font-weight-normal"
                            href="{% url 'accounting:rec_payment' invoice.id %}">
                            Payment
                        </a>

                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td class="text-center" colspan="100">No Invoices Available</td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
        <hr>
    </div>

    <div class="col-12">
        <h4>Unit Description</h4>
        <p style="white-space: pre-line;" class="mt-n4">
            {{unit.description}}
        </p>
    </div>
</div>
{% endblock body %}